import AudioDef as AD

##
## DisplayName[0] == CommandName[0]
## 1:1, so make sure they are the in the same position in the list!
##

DisplayName = [
"SmashBroDrillRemix",
"UltraInstinct",
"DSoulsBossMusic",
"DSoulsDeath",
"ArabicRingtone",
"SamsungStartUp",
"VineBoom",
"RobloxOof",
"SteveOof",
"OhHarderDaddy",
"OsmanthusWine",
"YTFULying",

"KahootLobby",
"ToBeContinued",
"SusImposterRole",
"SusBodyReported",
"EmotionalDamage",
"ISendU2Jesus",
"YouWhat",
"WHATTHEFUCK",
"WHAT",
"Shawty",
"OsManThuSWinE",
"McChallengeGet",

"ThunderStorm",
"BFGDivision",
"SmileDogMeme",
"Helicopter",
"WinXPShutDown",
"WinXPStartup",
"WinXPCritStop",
"WinXPError",
"SadHarmonica(!!!)",
"ReZeroGigguk",
"AnimeGirlAH",

"PHub",
"GTAWasted",
"GiornoThemePiano",
"SickoModeWaaah",
"DreamTranceMusic",
"IndianMusicMeme",
"DJAirhorn",
"WhatHow_Meme",
"SadHarmonica",
"Unravel",
"Yamete~",

"Bruh",
"JebNooo",
"ZoneAnkha",
"GangstaParadise",
"HeartFlatline",
"ChingChengHanji",
"SigmaMindset",
"MissTheRage",
"USSRAnthem",
"LionSleepsTonight",
"YameteKudasai~"
]

CommandName = [
AD.SmashBroDrillRemix,
AD.UltraInstinct,
AD.DSoulsBossMusic,
AD.DSoulsDeath,
AD.ArabicRingtone,
AD.SamsungStartUp,
AD.VineBoom,
AD.RobloxOof,
AD.SteveOof,
AD.OhHarderDaddy,
AD.OsmanthusWine,
AD.YTFULying,

AD.KahootLobby,
AD.ToBeContinued,
AD.SusImposterRole,
AD.SusBodyReported,
AD.EmotionalDamage,
AD.ISendU2Jesus,
AD.YouWhat,
AD.WHATTHEFUCK,
AD.WHAT,
AD.Shawty,
AD.OsManThuSWinE,
AD.McChallengeGet,

AD.ThunderStorm,
AD.BFGDivision,
AD.SmileDogMeme,
AD.Helicopterx2,
AD.WinXPShutDown,
AD.WinXPStartup,
AD.WinXPCritStop,
AD.WinXPError,
AD.SadHarmonicaEar,
AD.ReZeroGigguk,
AD.AnimeGirlAH,

AD.PHub,
AD.GTAWasted,
AD.GiornoThemePiano,
AD.SickoModeWaaah,
AD.DreamTranceMusic,
AD.IndianMusicMeme,
AD.DJAirhorn,
AD.WhatHow_Meme,
AD.SadHarmonica,
AD.Unravel,
AD.Yamete,

AD.Bruh,
AD.JebNooo,
AD.ZoneAnkha,
AD.GangstaParadise,
AD.HeartFlatline,
AD.ChingChengHanji,
AD.SigmaMindset,
AD.MissTheRage,
AD.USSRAnthem,
AD.LionSleepsTonight,
AD.YameteKudasai
]
