import AudioDef as AD

##
## DisplayName[0] == CommandName[0]
## 1:1, so make sure they are the in the same position in the list!
##

ComDispName = [
["SmashBroDrillRemix",AD.SmashBroDrillRemix],
["UltraInstinct",AD.UltraInstinct],
["DSoulsBossMusic",AD.DSoulsBossMusic],
["DSoulsDeath",AD.DSoulsDeath],
["ArabicRingtone",AD.ArabicRingtone],
["SamsungStartUp",AD.SamsungStartUp],
["VineBoom",AD.VineBoom],
["RobloxOof",AD.RobloxOof],
["SteveOof",AD.SteveOof],
["OhHarderDaddy",AD.OhHarderDaddy],
["OsmanthusWine",AD.OsmanthusWine],
["OsManThuSWinE",AD.OsManThuSWinE],
["KahootLobby",AD.KahootLobby],
["ToBeContinued",AD.ToBeContinued],
["SusImposterRole",AD.SusImposterRole],
["SusBodyReported",AD.SusBodyReported],
["EmotionalDamage",AD.EmotionalDamage],
["ISendU2Jesus",AD.ISendU2Jesus],
["YouWhat",AD.YouWhat],
["WHATTHEFUCK",AD.WHATTHEFUCK],
["WHAT",AD.WHAT],
["Shawty",AD.Shawty],
["YTFULying",AD.YTFULying],
["McChallengeGet",AD.McChallengeGet],
["ThunderStorm",AD.ThunderStorm],
["BFGDivision",AD.BFGDivision],
["SmileDogMeme",AD.SmileDogMeme],
["Helicopter*2",AD.Helicopterx2],
["WinXPShutDown",AD.WinXPShutDown],
["WinXPStartup",AD.WinXPStartup],
["WinXPCritStop",AD.WinXPCritStop],
["WinXPError",AD.WinXPError],
["ReZeroGigguk",AD.ReZeroGigguk],
["PHub",AD.PHub],
["GTAWasted",AD.GTAWasted],
["GiornoThemePiano",AD.GiornoThemePiano],
["SickoModeWaaah",AD.SickoModeWaaah],
["DreamTranceMusic",AD.DreamTranceMusic],
["IndianMusicMeme",AD.IndianMusicMeme],
["DJAirhorn",AD.DJAirhorn],
["WhatHow_Meme",AD.WhatHow_Meme],
["SadHarmonica(!!!)",AD.SadHarmonicaEar],
["SadHarmonica",AD.SadHarmonica],
["Unravel",AD.Unravel],
["AnimeGirlAH",AD.AnimeGirlAH],
["Yamete~",AD.Yamete],
["YameteKudasai~",AD.YameteKudasai],
["JebNooo",AD.JebNooo],
["Bruh",AD.Bruh],
["ZoneAnkha",AD.ZoneAnkha],
["GangstaParadise",AD.GangstaParadise],
["HeartFlatline",AD.HeartFlatline],
["ChingChengHanji",AD.ChingChengHanji],
["SigmaMindset",AD.SigmaMindset],
["MissTheRage",AD.MissTheRage],
["USSRAnthem",AD.USSRAnthem],
["LionSleepsTonight",AD.LionSleepsTonight]
]
